EB_TOP=../

# ----------------------------------------------------
# Target Specs 。
# ----------------------------------------------------
MODULES = englandArmy feardFarmers

COMPILE_FLAG = -I../

subdir:

include ../../make/target.mk 
