EB_TOP=../

# ----------------------------------------------------
# Target Specs 。
# ----------------------------------------------------
MODULES = englandArmy feardFarmers

COMPILE_FLAG = -I../

include ../../make/target.mk 
