EB_TOP=../../

# ----------------------------------------------------
# Target Specs 。
# ----------------------------------------------------
MODULES = erlbattle battlefield tools channel battleRecorder ebLogger\
			testAll testBattleFieldCreate testErlBattleTakeAction testErlBattleGetTime testEbLogger

include ../../make/target.mk 
