EB_TOP=../

# ----------------------------------------------------
# Target Specs
# ----------------------------------------------------
MODULES = erlbattle battlefield tools channel\
			englandArmy feardFarmers\
			testAll testBattleFieldCreate testErlBattleTakeAction testErlBattleGetTime

include ../make/target.mk 