EB_TOP=../../

# ----------------------------------------------------
# Target Specs ¡£
# ----------------------------------------------------
MODULES = bf fm fm_box info one scatter triple util      

COMPILE_FLAG = -I../../core

include ../../make/target.mk 
