EB_TOP=../

# ----------------------------------------------------
# Target Specs
# ----------------------------------------------------
MODULES = erlbattle englandArmy feardFarmers battlefield tools worldclock\
	testAll testBattleFieldCreate testErlBattleTakeAction testWorldClockGetTime

include ../make/target.mk 