{'*', [
      debug_info,
      {outdir, "ebin"}
      ]
}.

{'example_army/*',
        [debug_info,
        {outdir, "ebin"}
        ]
}.
{'neoedmund/*',
        [debug_info,
        {outdir, "ebin"}
        ]
}.

{'hwh/*',
	[
	{i, "hwh"},
	{outdir, "ebin/hwh"}
	]
}.
